//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOnTheFamily.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentStory
    {
        public int ContentStoryID { get; set; }
        public int ContentID { get; set; }
        public Nullable<System.Guid> RelatedProductID { get; set; }
        public string StoryTitle { get; set; }
        public string StoryText { get; set; }
        public string ImagePath { get; set; }
        public short displayOrder { get; set; }
    }
}
