//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOnTheFamily.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ProductID { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public short QtyAvail { get; set; }
        public string Authors { get; set; }
        public string ImagePath { get; set; }
    }
}
