//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOnTheFamily.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductDetailID { get; set; }
        public System.Guid ProductID { get; set; }
        public string DetailTitle { get; set; }
        public string DetailSummary { get; set; }
        public short DisplayOrder { get; set; }
    }
}
