USE [RTMDB]
GO

/****** Object:  Table [dbo].[MainPoints]    Script Date: 09/17/2015 13:41:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MainPoints](
	[MainPointId] [int] IDENTITY(1,1) NOT NULL,
	[MainPoint] [varchar](50) NULL,
	[MainPointDescription] [varchar](5000) NULL,
 CONSTRAINT [PK_MainPoints] PRIMARY KEY CLUSTERED 
(
	[MainPointId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

