USE [master]
GO

/****** Object:  Database [RTMDB]    Script Date: 09/17/2015 13:40:16 ******/
CREATE DATABASE [RTMDB] ON  PRIMARY 
( NAME = N'RTMDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\RTMDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RTMDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\RTMDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RTMDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RTMDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RTMDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RTMDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RTMDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RTMDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RTMDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RTMDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RTMDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RTMDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RTMDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RTMDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RTMDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RTMDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RTMDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RTMDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RTMDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RTMDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RTMDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RTMDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RTMDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RTMDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RTMDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RTMDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RTMDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RTMDB] SET  READ_WRITE 
GO

ALTER DATABASE [RTMDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RTMDB] SET  MULTI_USER 
GO

ALTER DATABASE [RTMDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RTMDB] SET DB_CHAINING OFF 
GO

